-
  name: 'FormBuilder'
  uriPattern: '{node}/form-builder/{--data.@action}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    '--data':
      '@package': 'CRON.FormBuilder'
      '@controller': 'FormBuilder'
      '@action': 'transfer'
      '@format': 'html'
  routeParts:
   node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: FALSE
